pool:
  name: Azure Pipelines
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'Free Trial (3b10f09f-004e-464b-8514-023e3d1af3f0)'
    azureContainerRegistry: '{"loginServer":"acr1ann.azurecr.io", "id" : "/subscriptions/3b10f09f-004e-464b-8514-023e3d1af3f0/resourceGroups/myapp-rg/providers/Microsoft.ContainerRegistry/registries/acr1ann"}'

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Free Trial (3b10f09f-004e-464b-8514-023e3d1af3f0)'
    azureContainerRegistry: '{"loginServer":"acr1ann.azurecr.io", "id" : "/subscriptions/3b10f09f-004e-464b-8514-023e3d1af3f0/resourceGroups/myapp-rg/providers/Microsoft.ContainerRegistry/registries/acr1ann"}'
    action: 'Push an image'

